from __future__ import annotations

from typing import Protocol

from stock_monitor.domain import AlertRule, MarketQuote, Stock


class StockRepository(Protocol):
    def add_stock(self, stock: Stock) -> None: ...

    def remove_stock(self, code: str) -> None: ...

    def list_stocks(self) -> list[Stock]: ...

    def add_alert(self, rule: AlertRule) -> int: ...

    def list_alerts(self) -> list[tuple[int, AlertRule]]: ...

    def mark_alert_triggered(self, alert_id: int) -> None: ...


class MarketDataProvider(Protocol):
    def get_quote(self, stock: Stock) -> MarketQuote: ...

    def get_intraday_series(self, stock: Stock, count: int = 40) -> list[float]: ...

    def get_daily_close_series(self, stock: Stock, count: int = 30) -> list[float]: ...
